#!/bin/bash

set -e

config=/etc/caddy/config.json
base=/caddy_base.json
HTTPS_CERT_FILE="${HTTPS_CERT_FILE:-/certs/cert.pem}"
HTTPS_KEY_FILE="${HTTPS_KEY_FILE:-/certs/key.pem}"

# remove endpoints if not set
for ENDPOINT in ACTION_HOST PRESENTER_HOST AUTOUPDATE_HOST ICC_HOST SEARCH_HOST MEDIA_HOST MANAGE_HOST CLIENT_HOST VOTE_HOST KEYCLOAK_HOST; do
   if [ -z "${!ENDPOINT}" ]; then
     echo "Removing endpoint $ENDPOINT"
     jq ".apps.http.servers.srv0.routes |= map(select(.handle | any(.upstreams[]?.dial | contains(\"$ENDPOINT\") | not)))" "$base" > "$base.out"
     mv -f "$base.out" "$base"
   fi
done

cp $base $config

for var in $(grep -o '\$[A-Za-z_][A-Za-z0-9_]*' $config | sort | uniq | sed 's/\$//'); do
    echo "Checking variable $var"
    if [[ -z "${!var}" ]]; then
        echo "Variable $var is not set"
    fi
done

# substitute env vars
envsubst < "$config" > "$config.out" && mv -f "$config.out" "$config"

jq_write() {
  filter=$1
  jq "$filter" "$config" > "$config.out" && mv -f "$config.out" "$config"
}

### HTTPS ###
if [ -n "$ENABLE_LOCAL_HTTPS" ]; then
  [ -f "$HTTPS_CERT_FILE" ] && [ -f "$HTTPS_KEY_FILE" ] || {
    echo "ERROR: no local cert-files provided. Did you run make-localhost-cert.sh?"
    exit 1
  }
  jq_write ".apps.http.servers.srv0.tls_connection_policies = [{ certificate_selection: { any_tag: [ \"cert0\" ] }}]"
  jq_write ".apps.tls = { certificates: { load_files: [{ certificate: \"$HTTPS_CERT_FILE\", key: \"$HTTPS_KEY_FILE\", tags: [ \"cert0\" ] }] }}"
else
  if [ -n "$ENABLE_AUTO_HTTPS" ]; then
    if [ -n "$EXTERNAL_ADDRESS" ]; then
      echo "INFO: For the automatic https to work ports 443 and 80 of the host must be
  directed to 8000 and 8001 of this container"
      jq_write "del(.apps.http.servers.srv0.automatic_https)" # disabled in base
      jq_write ".apps.http.https_port = 8000"
      jq_write ".apps.http.http_port = 8001"
      jq_write ".apps.http.servers.srv0.routes[-1].match = [{ host: [\"$EXTERNAL_ADDRESS\"]}]"

      if [ -n "$ACME_ENDPOINT" ]; then
        jq_write ".apps.tls.automation.policies[0].issuers[0].ca = \"${ACME_ENDPOINT}\""
      fi
    else
      echo "ERROR: EXTERNAL_ADDRESS needed for automatic HTTPS / cert generation"
      exit 1
    fi
  fi
fi

### ALLOWED HOSTS ###
if [ -n "$ALLOWED_HOSTS" ]; then
  for host in $ALLOWED_HOSTS; do
    jq_write ".apps.http.servers.srv0.routes[-2].match[0].not[0].header.Host += [\"$host\"]"
  done
else
  jq_write "del(.apps.http.servers.srv0.routes[-2])"
fi

exec "$@"
